package domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.user_id
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.email
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.phone
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.mobile
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.company
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.create_dt
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private Date createDt;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.sync
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    private String sync;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.user_id
     * 
     * @return the value of t_user.user_id
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.user_id
     * 
     * @param userId
     *            the value for t_user.user_id
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
     * 
     * @return the value of t_user.name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
     * 
     * @param name
     *            the value for t_user.name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_name
     * 
     * @return the value of t_user.login_name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_name
     * 
     * @param loginName
     *            the value for t_user.login_name
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.email
     * 
     * @return the value of t_user.email
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.email
     * 
     * @param email
     *            the value for t_user.email
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
     * 
     * @return the value of t_user.password
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
     * 
     * @param password
     *            the value for t_user.password
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.phone
     * 
     * @return the value of t_user.phone
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.phone
     * 
     * @param phone
     *            the value for t_user.phone
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.mobile
     * 
     * @return the value of t_user.mobile
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.mobile
     * 
     * @param mobile
     *            the value for t_user.mobile
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.company
     * 
     * @return the value of t_user.company
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.company
     * 
     * @param company
     *            the value for t_user.company
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.create_dt
     * 
     * @return the value of t_user.create_dt
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.create_dt
     * 
     * @param createDt
     *            the value for t_user.create_dt
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.sync
     * 
     * @return the value of t_user.sync
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public String getSync() {
        return sync;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.sync
     * 
     * @param sync
     *            the value for t_user.sync
     * 
     * @mbggenerated Mon Dec 03 09:24:51 CST 2012
     */
    public void setSync(String sync) {
        this.sync = sync == null ? null : sync.trim();
    }
}